SELECT 'Brand' as table_name, COUNT(*) as row_count FROM "Brand"
UNION ALL SELECT 'User', COUNT(*) FROM "User"
UNION ALL SELECT 'Product', COUNT(*) FROM "Product"
UNION ALL SELECT 'Order', COUNT(*) FROM "Order"
UNION ALL SELECT 'SubOrder', COUNT(*) FROM "SubOrder"
UNION ALL SELECT 'OrderItem', COUNT(*) FROM "OrderItem"
UNION ALL SELECT 'Cart', COUNT(*) FROM "Cart"
UNION ALL SELECT 'CartItem', COUNT(*) FROM "CartItem"
UNION ALL SELECT 'WishlistItem', COUNT(*) FROM "WishlistItem"
UNION ALL SELECT 'BrandMember', COUNT(*) FROM "BrandMember"
UNION ALL SELECT 'Review', COUNT(*) FROM "Review"
UNION ALL SELECT 'Notification', COUNT(*) FROM "Notification"
UNION ALL SELECT 'UserActivity', COUNT(*) FROM "UserActivity"
UNION ALL SELECT 'NotificationPreference', COUNT(*) FROM "NotificationPreference"
UNION ALL SELECT 'UserPaymentMethod', COUNT(*) FROM "UserPaymentMethod";
