import type { Brand, Product } from "@/types/marketplace";

export const fallbackBrands: Brand[] = [
  {
    id: "b1",
    name: "Outfitters",
    slug: "outfitters",
    verified: true,
    description: "Contemporary western streetwear with clean tailoring and urban utility pieces.",
    logoUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
  },
  {
    id: "b2",
    name: "Breakout",
    slug: "breakout",
    verified: true,
    description: "Modern casualwear balancing denim heritage and seasonal statements.",
    logoUrl: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800",
  },
  {
    id: "b3",
    name: "Cougar",
    slug: "cougar",
    verified: true,
    description: "Refined outerwear, footwear, and premium textures for elevated everyday dressing.",
    logoUrl: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=800",
  },
];

export const fallbackProducts: Product[] = [
  {
    id: "p1",
    brandId: "b1",
    name: "Men Essential Crew Tee",
    slug: "men-essential-crew-tee",
    description: "Heavyweight cotton tee with structured shoulders.",
    descriptionLong:
      "Cut from compact cotton jersey with a clean matte finish. Designed with a reinforced neckline and boxy proportions for a contemporary western street fit.",
    pricePkr: 2990,
    topCategory: "Men",
    productType: "Top",
    subCategory: "T-Shirts",
    colors: ["Black", "White", "Graphite"],
    sizes: ["S", "M", "L", "XL"],
    badge: "New",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=1400",
    stock: 28,
    isActive: true,
    brand: fallbackBrands[0],
  },
  {
    id: "p2",
    brandId: "b2",
    name: "Men Knit Polo",
    slug: "men-knit-polo",
    description: "Textured polo with slim placket and tonal buttons.",
    descriptionLong:
      "A breathable knit polo made for sharp casual styling. Fine rib detailing at cuffs and hem gives a polished silhouette that transitions from daywear to evening.",
    pricePkr: 5190,
    topCategory: "Men",
    productType: "Top",
    subCategory: "Polo Shirts",
    colors: ["Black", "Stone"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=1400",
    stock: 16,
    isActive: true,
    brand: fallbackBrands[1],
  },
  {
    id: "p3",
    brandId: "b1",
    name: "Men V-Neck Jersey",
    slug: "men-vneck-jersey",
    description: "Soft drape V-neck with clean binding.",
    descriptionLong:
      "A premium V-neck essential in smooth jersey for elevated layering. Maintains structure while remaining breathable for all-day comfort.",
    pricePkr: 2590,
    topCategory: "Men",
    productType: "Top",
    subCategory: "V-Neck",
    colors: ["Black", "Charcoal", "White"],
    sizes: ["S", "M", "L", "XL"],
    badge: "Sale",
    offer: {
      percentage: 20,
      isActive: true,
    },
    imageUrl: "https://images.unsplash.com/photo-1527719327859-c6ce80353573?w=1400",
    stock: 34,
    isActive: true,
    brand: fallbackBrands[0],
  },
  {
    id: "p4",
    brandId: "b2",
    name: "Men Straight Denim",
    slug: "men-straight-denim",
    description: "Deep indigo straight-fit denim with minimal wash.",
    descriptionLong:
      "Engineered with durable stretch-denim and subtle fade treatment. A foundational bottom that balances comfort with a tailored straight profile.",
    pricePkr: 4890,
    topCategory: "Men",
    productType: "Bottom",
    subCategory: "Jeans",
    colors: ["Indigo", "Black Wash"],
    sizes: ["30", "32", "34", "36"],
    imageUrl: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=1400",
    stock: 24,
    isActive: true,
    brand: fallbackBrands[1],
  },
  {
    id: "p5",
    brandId: "b1",
    name: "Men Cargo Trousers",
    slug: "men-cargo-trousers",
    description: "Utility pocket trousers in matte twill.",
    descriptionLong:
      "Clean utility styling with functional side pockets and tapered hem. Built for versatile city dressing with a strong monochrome visual language.",
    pricePkr: 5790,
    topCategory: "Men",
    productType: "Bottom",
    subCategory: "Cargo Pants",
    colors: ["Black", "Olive"],
    sizes: ["30", "32", "34", "36"],
    offer: {
      percentage: 18,
      isActive: true,
    },
    imageUrl: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=1400",
    stock: 18,
    isActive: true,
    brand: fallbackBrands[0],
  },
  {
    id: "p6",
    brandId: "b3",
    name: "Men Leather Sneakers",
    slug: "men-leather-sneakers",
    description: "Minimal leather cupsole sneakers.",
    descriptionLong:
      "Crafted with a clean low-top profile and cushioned insole. A premium essential for elevated everyday looks.",
    pricePkr: 9490,
    topCategory: "Men",
    productType: "Footwear",
    subCategory: "Sneakers",
    colors: ["Black", "White"],
    sizes: ["40", "41", "42", "43", "44"],
    badge: "New",
    offer: {
      percentage: 15,
      isActive: true,
    },
    imageUrl: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?w=1400",
    stock: 14,
    isActive: true,
    brand: fallbackBrands[2],
  },
  {
    id: "p7",
    brandId: "b3",
    name: "Men Chelsea Boots",
    slug: "men-chelsea-boots",
    description: "Polished ankle boots with elastic side panel.",
    descriptionLong:
      "A sharp western boot silhouette with a sculpted sole and premium upper. Designed for both formal and casual styling.",
    pricePkr: 10990,
    topCategory: "Men",
    productType: "Footwear",
    subCategory: "Boots",
    colors: ["Black"],
    sizes: ["40", "41", "42", "43"],
    badge: "Limited",
    imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=1400",
    stock: 11,
    isActive: true,
    brand: fallbackBrands[2],
  },
  {
    id: "p8",
    brandId: "b2",
    name: "Men Matte Belt",
    slug: "men-matte-belt",
    description: "Leather belt with tonal buckle.",
    descriptionLong:
      "A precision-cut belt with subtle matte hardware to complement monochrome wardrobes.",
    pricePkr: 2990,
    topCategory: "Men",
    productType: "Accessories",
    subCategory: "Belts",
    colors: ["Black", "Brown"],
    sizes: ["S", "M", "L"],
    imageUrl: "https://images.unsplash.com/photo-1611923134239-b9be5816f5af?w=1400",
    stock: 36,
    isActive: true,
    brand: fallbackBrands[1],
  },
  {
    id: "p9",
    brandId: "b1",
    name: "Women Cropped Poplin Shirt",
    slug: "women-cropped-poplin-shirt",
    description: "Crisp cropped shirt with tailored lines.",
    descriptionLong:
      "Structured poplin shirt with a minimalist cut and sharp collar. Ideal for smart layering with denim or skirts.",
    pricePkr: 4590,
    topCategory: "Women",
    productType: "Top",
    subCategory: "Formal Shirts",
    colors: ["White", "Black"],
    sizes: ["XS", "S", "M", "L"],
    imageUrl: "https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?w=1400",
    stock: 22,
    isActive: true,
    brand: fallbackBrands[0],
  },
  {
    id: "p10",
    brandId: "b2",
    name: "Women Satin V-Neck Top",
    slug: "women-satin-vneck-top",
    description: "Fluid satin top with flattering V-neck.",
    descriptionLong:
      "Soft satin drape and clean seam work make this an ideal evening transition piece for modern wardrobes.",
    pricePkr: 3990,
    topCategory: "Women",
    productType: "Top",
    subCategory: "V-Neck",
    colors: ["Black", "Champagne"],
    sizes: ["XS", "S", "M", "L"],
    badge: "Sale",
    offer: {
      percentage: 25,
      isActive: true,
    },
    imageUrl: "https://images.unsplash.com/photo-1495385794356-15371f348c31?w=1400",
    stock: 27,
    isActive: true,
    brand: fallbackBrands[1],
  },
  {
    id: "p11",
    brandId: "b2",
    name: "Women Straight Denim",
    slug: "women-straight-denim",
    description: "High-rise denim with clean straight leg.",
    descriptionLong:
      "Structured denim with balanced stretch and precise rise. Designed to pair across seasonal tops and outerwear.",
    pricePkr: 4990,
    topCategory: "Women",
    productType: "Bottom",
    subCategory: "Jeans",
    colors: ["Indigo", "Black Wash"],
    sizes: ["28", "30", "32", "34"],
    imageUrl: "https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?w=1400",
    stock: 21,
    isActive: true,
    brand: fallbackBrands[1],
  },
  {
    id: "p12",
    brandId: "b1",
    name: "Women Pleated Skirt",
    slug: "women-pleated-skirt",
    description: "Structured pleated midi skirt.",
    descriptionLong:
      "A modern pleated silhouette in durable fabric designed for clean movement and contemporary styling.",
    pricePkr: 5490,
    topCategory: "Women",
    productType: "Bottom",
    subCategory: "Skirts",
    colors: ["Black", "Stone"],
    sizes: ["XS", "S", "M", "L"],
    imageUrl: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=1400",
    stock: 18,
    isActive: true,
    brand: fallbackBrands[0],
  },
  {
    id: "p13",
    brandId: "b3",
    name: "Women Chunky Sneakers",
    slug: "women-chunky-sneakers",
    description: "Statement sole sneakers with breathable lining.",
    descriptionLong:
      "Designed for comfort and edge, with a sculpted outsole and mixed texture upper for contemporary styling.",
    pricePkr: 9390,
    topCategory: "Women",
    productType: "Footwear",
    subCategory: "Sneakers",
    colors: ["White", "Black"],
    sizes: ["37", "38", "39", "40"],
    badge: "New",
    offer: {
      percentage: 22,
      isActive: true,
    },
    imageUrl: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=1400",
    stock: 13,
    isActive: true,
    brand: fallbackBrands[2],
  },
  {
    id: "p14",
    brandId: "b2",
    name: "Women Crossbody Bag",
    slug: "women-crossbody-bag",
    description: "Compact crossbody with structured profile.",
    descriptionLong:
      "A practical premium accessory with clean hardware and interior organizer for everyday essentials.",
    pricePkr: 6790,
    topCategory: "Women",
    productType: "Accessories",
    subCategory: "Bags",
    colors: ["Black", "Tan"],
    sizes: ["One Size"],
    imageUrl: "https://images.unsplash.com/photo-1591561954555-607968c989ab?w=1400",
    stock: 25,
    isActive: true,
    brand: fallbackBrands[1],
  },
  {
    id: "p15",
    brandId: "b3",
    name: "Women Layered Necklace",
    slug: "women-layered-necklace",
    description: "Minimal layered necklace for evening edits.",
    descriptionLong:
      "Understated metallic layering piece designed to complement monochrome tailoring and fluid silhouettes.",
    pricePkr: 2390,
    topCategory: "Women",
    productType: "Accessories",
    subCategory: "Jewelry",
    colors: ["Silver", "Gold"],
    sizes: ["One Size"],
    badge: "Limited",
    imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=1400",
    stock: 42,
    isActive: true,
    brand: fallbackBrands[2],
  },
  {
    id: "p16",
    brandId: "b1",
    name: "Kids Graphic Hoodie",
    slug: "kids-graphic-hoodie",
    description: "Brushed fleece hoodie with clean chest print.",
    descriptionLong:
      "Soft-touch fleece hoodie engineered for comfort and durability, ideal for daily wear and cooler weather.",
    pricePkr: 3290,
    topCategory: "Kids",
    productType: "Top",
    subCategory: "Hoodies",
    colors: ["Black", "Heather Grey"],
    sizes: ["4Y", "6Y", "8Y", "10Y"],
    imageUrl: "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=1400",
    stock: 39,
    isActive: true,
    brand: fallbackBrands[0],
  },
  {
    id: "p17",
    brandId: "b2",
    name: "Kids Polo Tee",
    slug: "kids-polo-tee",
    description: "Soft polo with ribbed collar and sporty placket.",
    descriptionLong:
      "Breathable cotton blend polo designed for movement and easy care with structured everyday styling.",
    pricePkr: 2490,
    topCategory: "Kids",
    productType: "Top",
    subCategory: "Polo Shirts",
    colors: ["Navy", "White"],
    sizes: ["4Y", "6Y", "8Y", "10Y"],
    badge: "Sale",
    offer: {
      percentage: 12,
      isActive: true,
    },
    imageUrl: "https://images.unsplash.com/photo-1519238363430-6d56c844d0a5?w=1400",
    stock: 45,
    isActive: true,
    brand: fallbackBrands[1],
  },
  {
    id: "p18",
    brandId: "b2",
    name: "Kids Cargo Joggers",
    slug: "kids-cargo-joggers",
    description: "Elastic joggers with utility pockets.",
    descriptionLong:
      "Flexible waistband and reinforced seams provide durability, while utility styling adds a modern edge.",
    pricePkr: 2790,
    topCategory: "Kids",
    productType: "Bottom",
    subCategory: "Joggers",
    colors: ["Black", "Olive"],
    sizes: ["4Y", "6Y", "8Y", "10Y"],
    imageUrl: "https://images.unsplash.com/photo-1582418702059-97ebafb35d09?w=1400",
    stock: 31,
    isActive: true,
    brand: fallbackBrands[1],
  },
  {
    id: "p19",
    brandId: "b3",
    name: "Kids Slip-On Sneakers",
    slug: "kids-slip-on-sneakers",
    description: "Lightweight slip-on sneakers with grip sole.",
    descriptionLong:
      "Breathable knit upper and anti-slip sole designed for active comfort throughout the day.",
    pricePkr: 3590,
    topCategory: "Kids",
    productType: "Footwear",
    subCategory: "Slip Ons",
    colors: ["Black", "Blue"],
    sizes: ["28", "30", "32", "34"],
    imageUrl: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=1400",
    stock: 24,
    isActive: true,
    brand: fallbackBrands[2],
  },
  {
    id: "p20",
    brandId: "b1",
    name: "Kids Everyday Cap",
    slug: "kids-everyday-cap",
    description: "Adjustable structured cap in cotton twill.",
    descriptionLong:
      "Durable kids cap with sweatband lining and adjustable strap for flexible fit and all-season styling.",
    pricePkr: 1490,
    topCategory: "Kids",
    productType: "Accessories",
    subCategory: "Caps",
    colors: ["Black", "Navy", "Red"],
    sizes: ["One Size"],
    badge: "Out of Stock",
    imageUrl: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=1400",
    stock: 0,
    isActive: true,
    brand: fallbackBrands[0],
  },
];
